# Generated by Django 5.2.10 on 2026-02-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('customer_id', models.CharField(max_length=50)),
                ('customer_type', models.CharField(max_length=20)),
                ('account_age_days', models.IntegerField()),
                ('transaction_amount', models.FloatField()),
                ('merchant_category', models.CharField(max_length=100)),
                ('city_population', models.IntegerField()),
                ('payment_status', models.CharField(max_length=20)),
                ('fraud_label', models.BooleanField()),
                ('fraud_score', models.FloatField(default=0.0)),
                ('decision_status', models.CharField(default='approved', max_length=20)),
                ('ingested_at', models.DateTimeField()),
            ],
        ),
    ]
